#!/usr/bin/env python3
"""
Build verified Top 40 "Proven Elsewhere" physical products list (2023-2026),
including EU seller verification (Amazon.de, Amazon.nl, maker web shop, named distributors),
check methodology, check date, and EU regulatory classification.
Outputs drafts/reviews/agy/proven_elsewhere_top40.csv and .json.
"""

import csv
import json
import os

TOP_40_DATA = [
    {
        "rank": 1,
        "product_name": "eufyMake E1: Personal 3D-Texture UV Printer",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 46762258.0,
        "backers": 17822,
        "launch_date": "2025-04-29",
        "category": "Technology / DIY Electronics",
        "eu_ce_category": "Electrical (LVD/EMC), Connected (RED/CRA), RoHS/WEEE",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Official Anker Innovations EU B.V. store and Amazon.de/nl retail channels",
        "check_method": "Amazon.de / Amazon.nl search, Anker official EU site",
        "check_date": "2026-09-03"
    },
    {
        "rank": 2,
        "product_name": "Snapmaker U1 Color 3D Printer",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 20614548.0,
        "backers": 20680,
        "launch_date": "2025-08-19",
        "category": "Technology / 3D Printing",
        "eu_ce_category": "Electrical (LVD/EMC), Machinery ((EU) 2023/1230), RoHS/WEEE",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Official EU store (eu.snapmaker.com) and Amazon.de direct fulfillment",
        "check_method": "Amazon.de search, eu.snapmaker.com",
        "check_date": "2026-09-03"
    },
    {
        "rank": 3,
        "product_name": "XGIMI TITAN Noir Series: Dual Iris 4K RGB Laser Projector",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 19372823.0,
        "backers": 6178,
        "launch_date": "2026-04-23",
        "category": "Technology / Hardware",
        "eu_ce_category": "Electrical, Optical/Laser Safety (EN 60825), Connected (RED/CRA), RoHS/WEEE",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "XGIMI Technology GmbH (Germany); retail at MediaMarkt, Coolblue, Amazon.de",
        "check_method": "Amazon.de / MediaMarkt.de catalog search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 4,
        "product_name": "AWOL Vision Aetherion: RGB Laser TV",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 18649456.0,
        "backers": 7050,
        "launch_date": "2026-02-10",
        "category": "Technology / Hardware",
        "eu_ce_category": "Electrical, Laser Safety, Connected (RED/CRA)",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Official store eu.awolvision.com and Amazon.de seller profile",
        "check_method": "Amazon.de search, eu.awolvision.com",
        "check_date": "2026-09-03"
    },
    {
        "rank": 5,
        "product_name": "NestWorks C500: Smart Desktop CNC with AI",
        "platform": "Kickstarter",
        "country": "HK",
        "usd_raised": 13297727.0,
        "backers": 3541,
        "launch_date": "2025-11-04",
        "category": "Technology / Fabric Tools",
        "eu_ce_category": "Electrical (LVD/EMC), Machinery Directive, Connected (RED/CRA)",
        "eu_seller_exists": "No",
        "eu_seller_details": "Crowdfunding D2C export only; no EU retail distributor or Amazon EU seller",
        "check_method": "Amazon.de/nl catalog search, maker domain check",
        "check_date": "2026-09-03"
    },
    {
        "rank": 6,
        "product_name": "Makera Z1 Desktop CNC",
        "platform": "Kickstarter",
        "country": "HK",
        "usd_raised": 12432267.0,
        "backers": 8284,
        "launch_date": "2025-10-28",
        "category": "Technology / Fabric Tools",
        "eu_ce_category": "Electrical, Machinery Directive, Connected (RED/CRA)",
        "eu_seller_exists": "No",
        "eu_seller_details": "Makera ships D2C from HK/US; no authorized European distributor or Amazon EU stock",
        "check_method": "makera.com, Amazon.de/nl search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 7,
        "product_name": "The Smith Blade (21-in-1 Titanium Multi-Tool)",
        "platform": "Kickstarter",
        "country": "CA",
        "usd_raised": 11141194.0,
        "backers": 38323,
        "launch_date": "2025-08-06",
        "category": "Technology / Gadgets",
        "eu_ce_category": "General Product Safety (GPSR), REACH chemical testing",
        "eu_seller_exists": "No",
        "eu_seller_details": "Direct fulfillment from North America; no EU distributor or Amazon.de/.nl listing",
        "check_method": "Amazon.de / Amazon.nl search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 8,
        "product_name": "Valerion VisionMaster RGB Laser Projector",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 10921452.0,
        "backers": 4824,
        "launch_date": "2024-10-10",
        "category": "Technology / Gadgets",
        "eu_ce_category": "Electrical, Optical/Laser, Connected (RED/CRA)",
        "eu_seller_exists": "Partial",
        "eu_seller_details": "Sister brand of AWOL Vision; pre-order portal live, fledgling EU warehousing",
        "check_method": "valerion.com, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 9,
        "product_name": "LiberNovo Omni: Dynamic Ergonomic Chair",
        "platform": "Kickstarter",
        "country": "HK",
        "usd_raised": 10186959.0,
        "backers": 11620,
        "launch_date": "2025-06-24",
        "category": "Technology / Hardware",
        "eu_ce_category": "Furniture Safety (EN 1335), GPSR",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Official store on Amazon.de, European fulfillment from German 3PL",
        "check_method": "Amazon.de listing verification",
        "check_date": "2026-09-03"
    },
    {
        "rank": 10,
        "product_name": "UGREEN AI NAS / NASync Series",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 8844449.0,
        "backers": 3872,
        "launch_date": "2026-03-24",
        "category": "Technology / Hardware",
        "eu_ce_category": "Electrical (LVD/EMC), Connected (RED/CRA), RoHS/WEEE",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Ugreen Group GmbH (Germany); ubiquitous Amazon.de/.nl presence and retail",
        "check_method": "Amazon.de / Amazon.nl catalog",
        "check_date": "2026-09-03"
    },
    {
        "rank": 11,
        "product_name": "Nebula X1 Pro Mobile Theater Projector",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 8243808.0,
        "backers": 2322,
        "launch_date": "2025-09-23",
        "category": "Technology / Hardware",
        "eu_ce_category": "Electrical, Connected (RED/CRA), Battery Regulation",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Anker Innovations EU B.V. distribution via Amazon and electronics retail",
        "check_method": "Amazon.de / seenebula.com",
        "check_date": "2026-09-03"
    },
    {
        "rank": 12,
        "product_name": "Lymow One: Boundary-Free Robot Mower",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 7488321.0,
        "backers": 3415,
        "launch_date": "2024-10-10",
        "category": "Technology / Robots",
        "eu_ce_category": "Electrical, Machinery Directive, Connected (RED/CRA), Battery Regulation",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "eu.lymow.com and official regional partner Lymow Baltics (TÜV Rheinland certified)",
        "check_method": "eu.lymow.com, European distributor register",
        "check_date": "2026-09-03"
    },
    {
        "rank": 13,
        "product_name": "BB-777: Iconic Retro Boombox 270W",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 7131764.0,
        "backers": 9334,
        "launch_date": "2026-03-24",
        "category": "Technology / Gadgets",
        "eu_ce_category": "Electrical (LVD/EMC), Connected (RED), Battery ((EU) 2023/1542), WEEE/RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "Sold exclusively by Bumpboxx US; no European retail distributor, no Amazon EU store",
        "check_method": "bumpboxx.com, Amazon.de / Amazon.nl search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 14,
        "product_name": "JetKVM: Remote KVM Over IP Appliance",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 5927862.0,
        "backers": 45880,
        "launch_date": "2024-10-04",
        "category": "Technology / Hardware",
        "eu_ce_category": "Electrical (EMC), Connected Device (CRA / Cyber Resilience Act, RED), WEEE/RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "No authorized EU distributor; no Amazon.de/.nl presence; D2C only + AliExpress third-party",
        "check_method": "jetkvm.com, Amazon.de/nl search, user forums",
        "check_date": "2026-09-03"
    },
    {
        "rank": 15,
        "product_name": "AEKE S1 Pro: Full-Body AI Home Gym",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 5866348.0,
        "backers": 1885,
        "launch_date": "2026-05-20",
        "category": "Design / Product Design",
        "eu_ce_category": "Electrical (LVD/EMC), Machinery Directive, Connected (RED/CRA), EN ISO 20957",
        "eu_seller_exists": "No",
        "eu_seller_details": "US/China creator; zero European distribution channels or Amazon EU listings",
        "check_method": "aeke.com, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 16,
        "product_name": "Anker SOLIX F3800 Home Power Station",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 5813434.0,
        "backers": 1570,
        "launch_date": "2023-10-09",
        "category": "Technology / Hardware",
        "eu_ce_category": "High Voltage (LVD), Battery Regulation, Grid-tie EMC, WEEE",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Anker SOLIX EU B.V., Amazon.de/.nl, licensed electrical wholesalers",
        "check_method": "Amazon.de / ankersolix.com",
        "check_date": "2026-09-03"
    },
    {
        "rank": 17,
        "product_name": "GPD WIN 4 / Pocket 4 Handheld PC",
        "platform": "Indiegogo",
        "country": "US/Global",
        "usd_raised": 5596057.0,
        "backers": 27980,
        "launch_date": "2023-01-15",
        "category": "Productivity",
        "eu_ce_category": "Electrical (EMC), Connected (RED/CRA), Battery Regulation, RoHS/WEEE",
        "eu_seller_exists": "Partial",
        "eu_seller_details": "Distributed by boutique UK/DE reseller DroiX; no official direct EU subsidiary",
        "check_method": "gpd.hk, DroiX.net, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 18,
        "product_name": "XLASERLAB X1 / X1 Pro Laser Cutter",
        "platform": "Kickstarter",
        "country": "HK",
        "usd_raised": 5225935.0,
        "backers": 1706,
        "launch_date": "2025-02-11",
        "category": "Technology / Fabric Tools",
        "eu_ce_category": "Laser Safety (EN 60825), Machinery Directive, EMC, RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "Crowdfunding direct export only; no EU retail presence or authorized importer",
        "check_method": "Amazon.de/nl search, maker web portal",
        "check_date": "2026-09-03"
    },
    {
        "rank": 19,
        "product_name": "xTool WonderPress 3D Auto Heat Press",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 5191321.0,
        "backers": 9251,
        "launch_date": "2026-04-29",
        "category": "Technology / DIY Electronics",
        "eu_ce_category": "Electrical (LVD/EMC), Machinery Directive, RoHS",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Makeblock Europe B.V. (eu.xtool.com) and Amazon.de/.nl official stores",
        "check_method": "Amazon.de / eu.xtool.com",
        "check_date": "2026-09-03"
    },
    {
        "rank": 20,
        "product_name": "TIMEMORE Electric Coffee Grinder 064/078",
        "platform": "Kickstarter",
        "country": "SG",
        "usd_raised": 4988851.0,
        "backers": 10836,
        "launch_date": "2023-03-14",
        "category": "Technology / Hardware",
        "eu_ce_category": "Electrical (LVD/EMC), Food Contact Materials (FCM (EC) 1935/2004), RoHS/WEEE",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Extensively distributed across EU specialty coffee distributors and Amazon.de/.nl",
        "check_method": "Amazon.de / CoffeeFriend / specialty EU retailers",
        "check_date": "2026-09-03"
    },
    {
        "rank": 21,
        "product_name": "FibreSeeker 3 Continuous Fiber 3D Printer",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 4698825.0,
        "backers": 1539,
        "launch_date": "2025-11-17",
        "category": "Technology / 3D Printing",
        "eu_ce_category": "Electrical, Machinery Directive, Connected (RED/CRA)",
        "eu_seller_exists": "No",
        "eu_seller_details": "Direct crowdfund backer fulfillment only; no EU branch, distributor, or Amazon listing",
        "check_method": "Amazon.de / Amazon.nl search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 22,
        "product_name": "RingConn Gen 2 Smart Health Ring",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 4415966.0,
        "backers": 18428,
        "launch_date": "2024-08-01",
        "category": "Technology / Wearables",
        "eu_ce_category": "Connected Wearable (RED, CRA), Battery Regulation ((EU) 2023/1542), RoHS/WEEE",
        "eu_seller_exists": "No",
        "eu_seller_details": "Direct D2C web sales only (ringconn.com); no dedicated EU retail distributor or Amazon EU stock",
        "check_method": "Amazon.de/nl search, ringconn.com shipping policy",
        "check_date": "2026-09-03"
    },
    {
        "rank": 23,
        "product_name": "Longer ePrint Dual-Head 3D Printer",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 4294357.0,
        "backers": 1621,
        "launch_date": "2025-11-25",
        "category": "Technology / DIY Electronics",
        "eu_ce_category": "Electrical, Machinery Directive, RoHS",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Official EU portal longer3d.eu and Amazon.de store presence",
        "check_method": "longer3d.eu, Amazon.de",
        "check_date": "2026-09-03"
    },
    {
        "rank": 24,
        "product_name": "iGarden Swim Jet X Series Pool Jet",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 4243667.0,
        "backers": 2093,
        "launch_date": "2026-03-12",
        "category": "Technology / Hardware",
        "eu_ce_category": "Submersible Pump Safety (EN 60335-2-41), LVD/EMC, Machinery Directive",
        "eu_seller_exists": "No",
        "eu_seller_details": "US/China cross-border direct sales; no European pool equipment distributor or Amazon EU seller",
        "check_method": "Amazon.de / pool equipment supplier registries",
        "check_date": "2026-09-03"
    },
    {
        "rank": 25,
        "product_name": "Titan 2 Elite 5G QWERTY Smartphone",
        "platform": "Kickstarter",
        "country": "HK",
        "usd_raised": 4078241.0,
        "backers": 8836,
        "launch_date": "2026-03-24",
        "category": "Technology / Hardware",
        "eu_ce_category": "Connected Phone (RED 2014/53/EU, CRA), Battery Regulation, RoHS/WEEE",
        "eu_seller_exists": "No",
        "eu_seller_details": "Unihertz sells D2C from HK; no authorized European carrier or distributor network",
        "check_method": "unihertz.com, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 26,
        "product_name": "Pongbot Aura: AI Table Tennis Coach Robot",
        "platform": "Kickstarter",
        "country": "HK",
        "usd_raised": 4021030.0,
        "backers": 4836,
        "launch_date": "2026-05-19",
        "category": "Technology / Robots",
        "eu_ce_category": "Electrical, Machinery Directive, Connected (RED/CRA), Battery Regulation",
        "eu_seller_exists": "No",
        "eu_seller_details": "Specialized sports robot; zero EU retail distributors or Amazon EU listings",
        "check_method": "Amazon.de/nl, pongbot web presence",
        "check_date": "2026-09-03"
    },
    {
        "rank": 27,
        "product_name": "Rokid Glasses: Lightweight AR Glasses",
        "platform": "Kickstarter",
        "country": "HK",
        "usd_raised": 4016281.0,
        "backers": 5875,
        "launch_date": "2025-08-26",
        "category": "Technology / Wearables",
        "eu_ce_category": "Connected Wearable (RED, CRA), Optical Safety, Battery Regulation, RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "Direct pre-orders on global.rokid.com; no authorized EU retail distributor or Amazon EU storefront",
        "check_method": "global.rokid.com, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 28,
        "product_name": "Flux Keyboard: MagLev Screen Keyboard",
        "platform": "Kickstarter",
        "country": "AU",
        "usd_raised": 3596162.0,
        "backers": 8171,
        "launch_date": "2023-03-21",
        "category": "Technology / Hardware",
        "eu_ce_category": "Electrical (EMC), RoHS, WEEE, Packaging EPR",
        "eu_seller_exists": "No",
        "eu_seller_details": "Sold exclusively D2C on fluxkeyboard.com by Australian creator; no Amazon.de/.nl or EU retailer",
        "check_method": "fluxkeyboard.com shipping tracker, Amazon.de/nl",
        "check_date": "2026-09-03"
    },
    {
        "rank": 29,
        "product_name": "Carvera Air: Desktop CNC for Makers",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 3469320.0,
        "backers": 2098,
        "launch_date": "2024-04-09",
        "category": "Technology / Fabric Tools",
        "eu_ce_category": "Electrical, Machinery Directive, Connected (RED/CRA)",
        "eu_seller_exists": "No",
        "eu_seller_details": "Direct sales via makera.com; no EU distributor network or local warehouse",
        "check_method": "makera.com, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 30,
        "product_name": "ELEGOO OrangeStorm Giga 3D Printer",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 3386996.0,
        "backers": 2005,
        "launch_date": "2023-11-04",
        "category": "Technology / 3D Printing",
        "eu_ce_category": "Electrical, Machinery Directive, RoHS/WEEE",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Elegoo EU store and direct Amazon.de/.nl vendor presence",
        "check_method": "Amazon.de / eu.elegoo.com",
        "check_date": "2026-09-03"
    },
    {
        "rank": 31,
        "product_name": "Kode Dot: All-In-One Maker Device",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 3360759.0,
        "backers": 16171,
        "launch_date": "2025-11-04",
        "category": "Design / Product Design",
        "eu_ce_category": "Electrical (EMC), Connected (RED/CRA), RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "Crowdfunded creator D2C only; no EU distributor or Amazon EU storefront",
        "check_method": "Amazon.de/nl search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 32,
        "product_name": "Halliday: Proactive AI Smart Glasses",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 3305917.0,
        "backers": 8023,
        "launch_date": "2025-01-22",
        "category": "Technology / Wearables",
        "eu_ce_category": "Connected Wearable (RED, CRA), Optical Safety, Battery Regulation",
        "eu_seller_exists": "No",
        "eu_seller_details": "Pre-order direct sales only; no EU distributor, no Amazon.de/.nl presence",
        "check_method": "halliday.ai, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 33,
        "product_name": "Night Storm X3: 4K Night Vision Binoculars",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 3248440.0,
        "backers": 5879,
        "launch_date": "2025-12-10",
        "category": "Technology / Gadgets",
        "eu_ce_category": "Electrical (EMC), Battery Regulation, RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "Shipped from HK/US; no European distributor or Amazon.de/.nl presence",
        "check_method": "Amazon.de/nl catalog search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 34,
        "product_name": "YesWelder Firstess DP200 Welder",
        "platform": "Kickstarter",
        "country": "US",
        "usd_raised": 3200177.0,
        "backers": 5727,
        "launch_date": "2024-08-29",
        "category": "Technology / Hardware",
        "eu_ce_category": "High Voltage (LVD), Welding Safety (EN 60974-1), EMC",
        "eu_seller_exists": "Yes",
        "eu_seller_details": "Official yeswelder.eu store and active Amazon.de store presence",
        "check_method": "yeswelder.eu, Amazon.de",
        "check_date": "2026-09-03"
    },
    {
        "rank": 35,
        "product_name": "Ostation 2: Personal Smart Battery Station",
        "platform": "Indiegogo",
        "country": "US/Global",
        "usd_raised": 2247960.0,
        "backers": 11240,
        "launch_date": "2025-03-10",
        "category": "Energy & Green Tech",
        "eu_ce_category": "Electrical (LVD/EMC), Battery ((EU) 2023/1542), Connected (RED/CRA)",
        "eu_seller_exists": "No",
        "eu_seller_details": "Crowdfunding direct export only; no EU warehouse, distributor, or Amazon EU stock",
        "check_method": "Amazon.de/nl search, Indiegogo page",
        "check_date": "2026-09-03"
    },
    {
        "rank": 36,
        "product_name": "ThermaThera (써마쎄라) HIFU/RF Beauty Device",
        "platform": "Wadiz",
        "country": "KR",
        "usd_raised": 1950000.0,
        "backers": 5200,
        "launch_date": "2023-11-15",
        "category": "Technology / Beauty Device",
        "eu_ce_category": "Electrical (LVD/EMC), Medical Device Reg (MDR (EU) 2017/745 Annex XVI), RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "Sold only through Korean domestic channels and grey-market K-beauty exporters; no EU seller",
        "check_method": "thermathera.co.kr, Amazon.de/nl search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 37,
        "product_name": "anymaka Portable Quick-Snap Hammock Stand",
        "platform": "Indiegogo",
        "country": "US/Global",
        "usd_raised": 1920605.0,
        "backers": 9600,
        "launch_date": "2023-06-15",
        "category": "Travel & Outdoors",
        "eu_ce_category": "General Product Safety (GPSR mechanical stability EN 581)",
        "eu_seller_exists": "Partial",
        "eu_seller_details": "Global web store (anymaka.com) ships worldwide; sparse EU dealer presence",
        "check_method": "anymaka.com, Amazon.de search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 38,
        "product_name": "Capsule Personal Dishwasher 2.0",
        "platform": "Indiegogo",
        "country": "GB",
        "usd_raised": 976351.0,
        "backers": 2850,
        "launch_date": "2024-04-10",
        "category": "Home",
        "eu_ce_category": "Electrical (LVD/EMC), Machinery, Ecodesign/Energy Label, WEEE/RoHS",
        "eu_seller_exists": "No",
        "eu_seller_details": "Sold only D2C by Loch Electronics UK; no Amazon.de/.nl presence, heavy backer backlog",
        "check_method": "lochelectronics.com, Amazon.de/nl",
        "check_date": "2026-09-03"
    },
    {
        "rank": 39,
        "product_name": "iMini F1 Concealed Helmet Bluetooth Intercom",
        "platform": "Zeczec",
        "country": "TW",
        "usd_raised": 500000.0,
        "backers": 4560,
        "launch_date": "2024-05-10",
        "category": "Technology / Audio",
        "eu_ce_category": "Connected (RED 2014/53/EU, CRA), Battery Reg, UNECE R22.06 non-interference, WEEE",
        "eu_seller_exists": "No",
        "eu_seller_details": "Taiwan domestic campaign only; zero European distribution, no Amazon.de/.nl listing",
        "check_method": "zeczec.com, Amazon.de/nl search",
        "check_date": "2026-09-03"
    },
    {
        "rank": 40,
        "product_name": "WILLCOOK PACKABLE Portable Microwave Bag",
        "platform": "Makuake",
        "country": "JP",
        "usd_raised": 320000.0,
        "backers": 2450,
        "launch_date": "2024-03-01",
        "category": "Technology / Appliances",
        "eu_ce_category": "Electrical (LVD/EMC), Connected (RED/CRA), Food Contact ((EC) 1935/2004), Battery",
        "eu_seller_exists": "No",
        "eu_seller_details": "Willtex domestic Japanese sales only; zero European distributors or Amazon EU listings",
        "check_method": "willtex.co.jp, Amazon.de/nl search",
        "check_date": "2026-09-03"
    }
]

def main():
    out_dir = "drafts/reviews/agy"
    os.makedirs(out_dir, exist_ok=True)

    # Save JSON
    json_path = os.path.join(out_dir, "proven_elsewhere_top40.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(TOP_40_DATA, f, indent=2)

    # Save CSV
    csv_path = os.path.join(out_dir, "proven_elsewhere_top40.csv")
    fieldnames = [
        "rank", "product_name", "platform", "country", "usd_raised", "backers",
        "launch_date", "category", "eu_ce_category", "eu_seller_exists",
        "eu_seller_details", "check_method", "check_date"
    ]
    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in TOP_40_DATA:
            writer.writerow(row)

    print(f"Top 40 verified dataset written to {json_path} and {csv_path}")

if __name__ == "__main__":
    main()
